name: py37
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - anyio=2.2.0=py37h06a4308_1
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=3.3.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.5=py37h261ae71_0
  - chardet=4.0.0=py37h06a4308_1003
  - cryptography=3.4.7=py37hd23ed53_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - idna=2.10=pyhd3eb1b0_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter-packaging=0.7.12=pyhd3eb1b0_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37h06a4308_0
  - jupyter_server=1.4.1=py37h06a4308_0
  - jupyterlab=3.0.14=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.4.0=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - markupsafe=2.0.1=py37h27cfd23_0
  - mistune=0.8.4=py37h14c3975_1001
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py37h06a4308_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.1.2=py37h06a4308_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h12debd9_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37h06a4308_0
  - sniffio=1.2.0=py37h06a4308_1
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alembic==1.4.1
    - blis==0.7.4
    - boruta==0.3
    - bottleneck==1.3.2
    - catalogue==1.0.0
    - click==8.0.1
    - cloudpickle==1.6.0
    - colorlover==0.3.0
    - cufflinks==0.17.3
    - cycler==0.10.0
    - cymem==2.0.5
    - databricks-cli==0.14.3
    - decorator==4.4.2
    - docker==5.0.0
    - entrypoints==0.3
    - flask==2.0.1
    - funcy==1.16
    - future==0.18.2
    - gensim==3.8.3
    - gitdb==4.0.7
    - gitpython==3.1.17
    - greenlet==1.1.0
    - gunicorn==20.1.0
    - htmlmin==0.1.12
    - imagehash==4.2.0
    - imbalanced-learn==0.7.0
    - importlib-metadata==4.5.0
    - ipykernel==5.5.5
    - ipython==7.24.1
    - ipywidgets==7.6.3
    - itsdangerous==2.0.1
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - kmodes==0.11.0
    - lightgbm==3.2.1
    - llvmlite==0.36.0
    - mako==1.1.4
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - missingno==0.4.2
    - mlflow==1.17.0
    - mlxtend==0.18.0
    - multimethod==1.4
    - murmurhash==1.0.5
    - networkx==2.5.1
    - nltk==3.6.2
    - numba==0.53.1
    - numexpr==2.7.3
    - numpy==1.19.5
    - pandas==1.2.4
    - pandas-profiling==3.0.0
    - patsy==0.5.1
    - phik==0.11.2
    - pillow==8.2.0
    - plac==1.1.3
    - plotly==4.14.3
    - preshed==3.0.5
    - prometheus-flask-exporter==0.18.2
    - prompt-toolkit==3.0.18
    - protobuf==3.17.3
    - pycaret==2.3.1
    - pydantic==1.8.2
    - pyldavis==3.2.2
    - pynndescent==0.5.2
    - pyod==0.8.8
    - python-editor==1.0.4
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - querystring-parser==1.2.4
    - regex==2021.4.4
    - retrying==1.3.3
    - scikit-learn==0.23.2
    - scikit-plot==0.3.7
    - scipy==1.5.4
    - seaborn==0.11.1
    - six==1.16.0
    - smart-open==5.1.0
    - smmap==4.0.0
    - spacy==2.3.7
    - sqlalchemy==1.4.18
    - sqlparse==0.4.1
    - srsly==1.0.5
    - statsmodels==0.12.2
    - tabulate==0.8.9
    - tangled-up-in-unicode==0.1.0
    - terminado==0.10.1
    - testpath==0.5.0
    - textblob==0.15.3
    - thinc==7.4.5
    - threadpoolctl==2.1.0
    - tqdm==4.61.0
    - typing-extensions==3.10.0.0
    - umap-learn==0.5.1
    - urllib3==1.26.5
    - visions==0.7.1
    - wasabi==0.8.2
    - webencodings==0.5.1
    - websocket-client==1.1.0
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - wordcloud==1.8.1
    - yellowbrick==1.3.post1
prefix: /home/meftaul/miniconda3/envs/py37
